//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConversionModule.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class CurrencySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CurrencySettings defaultInstance = ((CurrencySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CurrencySettings())));
        
        public static CurrencySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrencyOptions {
            get {
                return ((string)(this["CurrencyOptions"]));
            }
            set {
                this["CurrencyOptions"] = value;
            }
        }
    }
}
